Добавление лаб 02

diff --git a/.github/workflows/classroom.yml b/.github/workflows/classroom.yml
--- a/.github/workflows/classroom.yml
+++ b/.github/workflows/classroom.yml
@@ -3,11 +3,90 @@ on:
   push:
     branches:
       - master
+      - develop
   pull_request:
     branches:
       - master
+      - develop
+
 jobs:
   build:
+    name: build
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: build tests
+        run: |
+          docker build -t loaylty:latest -f ./loyalty.dockerfile . --target=build
+          docker build -t payment:latest -f ./payment.dockerfile . --target=build
+          docker build -t reservation:latest -f ./reservation.dockerfile . --target=build
+          docker save loyalty:latest > loyalty_build.tar
+          docker save payment:latest > payment_build.tar
+          docker save reservation:latest > reservation_build.tar
+      - name: build backend
+        run: |
+          docker build -t loaylty:latest -f ./loyalty.dockerfile . --target=release
+          docker build -t payment:latest -f ./payment.dockerfile . --target=release
+          docker build -t reservation:latest -f ./reservation.dockerfile . --target=release
+          docker build -t gateway:latest -f ./gateway.dockerfile . --target=release
+          docker save loyalty:latest > loyalty_release.tar
+          docker save payment:latest > payment_release.tar
+          docker save reservation:latest > reservation_release.tar
+          docker save gateway:latest > gateway_release.tar
+      - uses: actions/upload-artifact@v4 
+        with: 
+          name: tests-artefact 
+          path: *_build.tar
+      - uses: actions/upload-artifact@v4 
+        with: 
+          name: backend-artefact 
+          path: *_release.tar
+
+  test:
+    name: test
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - uses: actions/download-artifact@v4
+        with: 
+          name: tests-artefact 
+      - name: run tests
+        run: |
+          docker load < loyalty_build.tar
+          docker load < payment_build.tar
+          docker load < reservation_build.tar
+          docker compose -f ./docker-compose.tests.yml up --exit-code-from tests
+          if [[ 0 == $? ]]
+          then
+            echo "TESTS_STATUS=success" >> $GITHUB_ENV
+          else
+            echo "TESTS_STATUS=failed" >> $GITHUB_ENV
+          fi
+
+  deploy:
+    name: run
+    runs-on: ubuntu-latest
+    needs: test
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - uses: actions/download-artifact@v4
+        with: 
+          name: backend-artefact 
+      - name: Run
+        run: |
+          docker load < loyalty_release.tar
+          docker load < payment_release.tar
+          docker load < reservation_release.tar
+          docker compose -f ./docker-compose.yml up
+
+  integration-tests:
     name: Autograding
     runs-on: ubuntu-latest
     steps:
@@ -16,27 +95,11 @@ jobs:
           fetch-depth: 0
 
       - uses: docker/setup-buildx-action@v2
-
-      # TODO build and run unit tests
-
-      - name: Build images
-        timeout-minutes: 10
-        run: docker compose build
-
-      - name: Run containers
-        timeout-minutes: 5
-        run: |
-          docker compose up -d
-          ./scripts/wait-script.sh
-        env:
-          WAIT_PORTS: 8080,8070,8060,8050
-
       - name: Run API Tests
         uses: matt-ball/newman-action@master
         with:
-          # TODO insert your variant
-          collection: <variant>/postman/collection.json
-          environment: <variant>/postman/environment.json
+          collection: v2/postman/collection.json
+          environment: v2/postman/environment.json
           delayRequest: 100
           reporters: '[ "cli" ]'
 
